Creación de diccionario de clientes morosos
dnlcarvajalc/villa_fc pull request #11
Opened 2024-01-15 23:01 UTC by JacoboMontenegroAngel

HU3 

Hice uso de "datetime" para tener la fecha real siempre, y poder convertir los datos tipo string del Excel, luego de esto realicé una operación para saber quiénes deben, con esta información cree el diccionario con el nombre de las personas que deben y su número telefónico

2024-01-15 23:04 UTC, dnlcarvajalc commented on src/cobros.py
> +fecha = datetime.now()
Revisar si esta variable global es necesaria

2024-01-15 23:05 UTC, dnlcarvajalc commented on src/cobros.py
> +     columnaD = df.iloc[:, constants.COLUM_NUMBER]
revisar la correcta escritura de las variables

2024-01-15 23:05 UTC, dnlcarvajalc commented on src/cobros.py
> +     columnaD = df.iloc[:, constants.COLUM_NUMBER]
columnaD a que corresponde? ¿que informacion obtengo de esto?

2024-01-15 23:06 UTC, dnlcarvajalc commented on src/cobros.py
> +def obtenerColumna (df):
Revisar en PEP8 cual es la correcta escritura de las funciones

2024-01-15 23:07 UTC, dnlcarvajalc commented on src/cobros.py
> +    df_new = pd.to_datetime(df['ULTIMO_PAGO'], format='%d/%m/%Y')
¿Es posible dejar el formato usado en el archivo de constantes?

2024-01-15 23:07 UTC, dnlcarvajalc commented on src/cobros.py
> +    print("holi")
que print tan profesional ¬¬

2024-01-15 23:08 UTC, dnlcarvajalc commented on src/cobros.py
> +    df_new['Diferencia'] = None
Por que se inicializa como None y no como un dataframe de pandas?

2024-01-15 23:08 UTC, dnlcarvajalc commented on src/cobros.py
> +        fecha_convertoda = conv_datetime(cliente)
Revisar el correcto deletreo de las constantes

2024-01-15 23:09 UTC, dnlcarvajalc commented on src/constants.py
> +COLUM_NUMBER = 3
Revisar la correcta escritura del column number

2024-01-15 23:09 UTC, dnlcarvajalc commented on src/cobros.py
> +    print(df_new)
los print son necesarios?

2024-01-15 23:10 UTC, dnlcarvajalc commented on src/villa.py
> +    cobros.resta_fechas(df)
¿que es resta_fechas? hay algun nombre mas diciente? a que variable lo igualamos para integrarlo con el resto del codigo?

2024-01-15 23:11 UTC, dnlcarvajalc requested changes
Por favor cambiar lo aqui expuesto.

2024-01-16 16:43 UTC, JacoboMontenegroAngel commented on src/cobros.py
> +fecha = datetime.now()
No es necesaria, entonces la cree dentro de la función

2024-01-16 16:44 UTC, JacoboMontenegroAngel commented on src/cobros.py
> +     columnaD = df.iloc[:, constants.COLUM_NUMBER]
No esta bien escrita porque debe ser separada por "_" y en minuscula. De igual forma esa función no es necesaria, entonces fue eliminada

2024-01-16 16:45 UTC, JacoboMontenegroAngel commented on src/cobros.py
> +    print("holi")
jeje

2024-01-16 20:39 UTC, dnlcarvajalc commented on src/cobros.py
> +        df (type): Data frame con toda la informacion de pagos
¿a que se refiere con type?

2024-01-16 20:50 UTC, dnlcarvajalc approved these changes

2024-01-16 21:21 UTC, merged